import Head from "next/head";
import client from "apollo-client";
import { gql } from "@apollo/client";
import { GetServerSideProps } from "next";
import { ReminderType } from "@/types/models/reminders";
import { RemindersPage } from "@/components/pages/RemindersPage";

export const getServerSideProps: GetServerSideProps<{
  reminders: ReminderType[];
}> = async () => {
  const { data } = await client.query({
    query: gql`
      query allReminders {
        allReminder {
          title
          isCompleted
          description
          dueAt
          _id
        }
      }
    `,
  });

  return {
    props: {
      reminders: data.allReminder,
    },
  };
};

export default function Home({ reminders }: { reminders: ReminderType[] }) {
  return (
    <>
      <Head>
        <title>Reminders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RemindersPage reminders={reminders} />
    </>
  );
}
